## TODO: use environment variables
version: "3.3"

services:
  db:
    image: mongo:latest
    networks:
      - todo_net
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
    ports:
      - "27017:27017"
    command:
#      --bind_ip 0.0.0.0 --auth
      --bind_ip 0.0.0.0        

  front_end:
    image: meditation-measured:latest
    ports:
      - "80:3000"
    networks:
      - todo_net
    environment:
      - DB_URL=mongodb://db:27017
      - DEBUG=app:*

networks:
  todo_net:
##### Experimental changes with different NW. DO NOT Enable below  
#    driver: bridge  
#    ipam:
#      config:
#      - subnet: 172.16.0.0/24
#        gateway: 172.16.0.254

volumes:
  dbdata:
